### ISSUE TITLE
[Request] Sombrero Rojo Explanation (fbctf)

### ISSUE THREAD

**Issue by ammarfaizi2** [Jinmo/ctfs#1]
Hello,
I am curious what is the technique and tool you've used to solve this one https://github.com/Jinmo/ctfs/blob/master/2019/fbctf/rev/sombrero_rojo.md
Could you write the detailed write up for this one?
Thank you in advance.

**Comment by Jinmo** [comment]
I'll update it in 2~3 days!

**Comment by Jinmo** [comment]
Just updated the post. If you have any suggestions, please let me know!
